// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztmjvnyjxuthccofqeng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0bWp2bnlqeHV0aGNjb2ZxZW5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4MDM1MjUsImV4cCI6MjA3NTM3OTUyNX0.C8QIQD27Qnd-Ni6APCLN9Y7GKff0uCD1bMocDkzJjnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});